spring:
    datasource:
        url: jdbc:mysql://192.168.100.22:3306/authentication
        username: dev
        password: Casa123++
    jpa:
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: validate
            naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

auth:
    expiration: 604800
    sub: sub
    create: created
    secret: n2r5u8x/ADGKaPdSgVkYp3s6v9yBEH+MbQeThWmZq4t7wzCFJNcRn2r5u8x/ADGKaPdSgVkYp3s6v9yBEH+MbQeThWmZq4t7wzCFJNcRff
    header: Authorization