spring:
    datasource:
        url: jdbc:mysql://localhost:3306/authentication
        username: root
        password: rootroot
    jpa:
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: validate
            naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

jwt:
    auth_login_url: /auth/login
#    7days
    expiration: 604800
    sub: sub
    create: created
    token_secret: n2r5u8x/ADGKaPdSgVkYp3s6v9yBEH+MbQeThWmZq4t7wzCFJNcRn2r5u8x/ADGKaPdSgVkYp3s6v9yBEH+MbQeThWmZq4t7wzCFJNcRff
    token_header: Authorization
    token_prefix: "Bearer "